name: Staging Deployment (PAUSED)

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**' # Renamed from backend-legacy
      - 'frontend-client/**'
      - 'frontend-admin/**'
      - 'helm/**'
      - '.github/workflows/**'

env:
  AWS_REGION: us-east-1
  ECR_REGISTRY: 268456953512.dkr.ecr.us-east-1.amazonaws.com
  IMAGE_TAG: ${{ github.sha }}
  GITOPS_REPO: ShaiMullo/crystolia-gitops

jobs:
  changes:
    name: 🔍 Detect Changes
    runs-on: ubuntu-latest
    outputs:
      backend: ${{ steps.filter.outputs.backend }}
      frontend_client: ${{ steps.filter.outputs.frontend_client }}
      frontend_admin: ${{ steps.filter.outputs.frontend_admin }}
    steps:
      - uses: actions/checkout@v4
      - name: Fix Git Safety
        run: git config --global --add safe.directory "*"
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            backend:
              - 'backend/**'
              - 'helm/**'
              - '.github/workflows/staging.yml'
            frontend_client:
              - 'frontend-client/**'
              - '.github/workflows/staging.yml'
            frontend_admin:
              - 'frontend-admin/**'
              - '.github/workflows/staging.yml'

  test-frontend-client:
    name: 🧪 Test Frontend Client
    needs: changes
    if: ${{ needs.changes.outputs.frontend_client == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Fix Git Safety
        run: git config --global --add safe.directory "*"
      - uses: actions/setup-node@v4
        with: { node-version: '20' }
      - run: npm ci
        working-directory: frontend-client
      - run: npm run lint || echo "Lint failed but proceeding"
        continue-on-error: true
        working-directory: frontend-client

  test-frontend-admin:
    name: 🧪 Test Frontend Admin
    needs: changes
    if: ${{ needs.changes.outputs.frontend_admin == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Fix Git Safety
        run: git config --global --add safe.directory "*"
      - uses: actions/setup-node@v4
        with: { node-version: '20' }
      - run: npm ci
        working-directory: frontend-admin
      - run: npm run lint || echo "Lint failed but proceeding"
        continue-on-error: true
        working-directory: frontend-admin

  build-dry-run:
    name: 🏗️ Build (Dry Run)
    needs: [ changes, test-frontend-client, test-frontend-admin ]
    # Run if ANY service changed
    if: ${{ always() && (needs.changes.outputs.backend == 'true' || needs.changes.outputs.frontend_client == 'true' || needs.changes.outputs.frontend_admin == 'true') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Fix Git Safety
        run: git config --global --add safe.directory "*"

      # AWS CREDENTIALS DISABLED
      # - uses: aws-actions/configure-aws-credentials@v4 ...
      # - uses: aws-actions/amazon-ecr-login@v2 ...

      # Build Backend (No Push)
      - name: Build Backend
        if: ${{ needs.changes.outputs.backend == 'true' }}
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: false # DISABLED
          tags: ${{ env.ECR_REGISTRY }}/crystolia-backend:${{ env.IMAGE_TAG }}

      # Build Frontend Client (No Push)
      - name: Build Frontend Client
        if: ${{ needs.changes.outputs.frontend_client == 'true' }}
        continue-on-error: true
        uses: docker/build-push-action@v5
        with:
          context: ./frontend-client
          file: ./frontend-client/Dockerfile
          push: false # DISABLED
          tags: ${{ env.ECR_REGISTRY }}/crystolia-frontend-client:${{ env.IMAGE_TAG }}

      # Build Frontend Admin (No Push)
      - name: Build Frontend Admin
        if: ${{ needs.changes.outputs.frontend_admin == 'true' }}
        continue-on-error: true
        uses: docker/build-push-action@v5
        with:
          context: ./frontend-admin
          file: ./frontend-admin/Dockerfile
          push: false # DISABLED
          tags: ${{ env.ECR_REGISTRY }}/crystolia-frontend-admin:${{ env.IMAGE_TAG }}
      # Deploy Step DISABLED
      # - name: Checkout GitOps Repo ...
