apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: mongodb
    targetRevision: 15.6.0
    helm:
      values: |
        image:
          registry: docker.io
          repository: mongo
          tag: "7"
        auth:
          enabled: false
        persistence:
          enabled: true
          size: 1Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: crystolia
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
